use crate::tray::TrayManager;
use crate::types::{RebuildFlowState, Route, RuntimeStatus, ToastStatus, Transition};
use iced::Theme;
use iced::widget::text_editor;
use infiltrator_core::rules::RuleEntry;
use infiltrator_desktop::MihomoRuntime;
use mihomo_api::{ConnectionSnapshot, TrafficData};
use mihomo_config::Profile;
use mihomo_version::manager::VersionInfo;
use std::collections::{HashMap, VecDeque};
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Instant;

pub struct AppState {
    pub current_route: Route,
    pub runtime: Option<Arc<MihomoRuntime>>,
    pub status: RuntimeStatus,
    pub error_msg: Option<String>,
    pub profiles: Vec<Profile>,
    pub profiles_filter: String,
    pub is_loading_profiles: bool,
    pub proxies: HashMap<String, mihomo_api::Proxy>,
    pub is_loading_proxies: bool,
    pub filtered_groups: Vec<(String, Vec<String>)>,
    pub transition: Transition,
    pub proxy_filter: String,
    pub proxy_sort_by_delay: bool,
    pub proxy_delay_sort: String,
    pub runtime_delay_test_url: String,
    pub runtime_delay_timeout_ms: String,
    pub runtime_testing_delay_proxy: String,
    pub runtime_testing_all_delays: bool,
    pub runtime_selected_group: String,
    pub runtime_selected_proxy: String,
    pub runtime_connection_filter: String,
    pub runtime_connection_sort: String,
    pub traffic: Option<TrafficData>,
    pub traffic_history: VecDeque<(u64, u64)>,
    pub runtime_prev_upload_total: Option<u64>,
    pub runtime_prev_download_total: Option<u64>,
    pub memory: Option<mihomo_api::MemoryData>,
    pub public_ip: Option<String>,
    pub connections: Option<ConnectionSnapshot>,
    pub logs: VecDeque<String>,
    pub log_level: String,
    pub runtime_auto_refresh: bool,
    pub runtime_poll_tick: u64,
    pub lang: String,
    pub proxy_mode: Option<String>,
    pub tun_enabled: Option<bool>,
    pub tun_stack: String,
    pub tun_auto_route: bool,
    pub tun_strict_route: bool,
    pub sniffer_enabled: bool,
    pub rules: Vec<RuleEntry>,
    pub rules_filter: String,
    pub is_loading_rules: bool,
    pub rules_loaded_once: bool,
    pub is_saving_rules: bool,
    pub rules_dirty: bool,
    pub rule_providers_json_content: text_editor::Content,
    pub proxy_providers_json_content: text_editor::Content,
    pub sniffer_json_content: text_editor::Content,
    pub rule_providers_json_dirty: bool,
    pub proxy_providers_json_dirty: bool,
    pub sniffer_json_dirty: bool,
    pub is_saving_rule_providers_json: bool,
    pub is_saving_proxy_providers_json: bool,
    pub is_saving_sniffer_json: bool,
    pub dns_json_content: text_editor::Content,
    pub fake_ip_json_content: text_editor::Content,
    pub tun_json_content: text_editor::Content,
    pub advanced_configs_loaded_once: bool,
    pub dns_json_dirty: bool,
    pub fake_ip_json_dirty: bool,
    pub tun_json_dirty: bool,
    pub new_rule_type: String,
    pub new_rule_payload: String,
    pub new_rule_target: String,
    pub is_adding_rule: bool,
    pub proxy_providers: Vec<mihomo_api::ProxyProvider>,
    pub rule_providers: Vec<mihomo_api::RuleProvider>,
    pub is_loading_providers: bool,
    pub tray_manager: Option<TrayManager>,
    pub dns_nameservers: Vec<String>,
    pub dns_fallback_servers: Vec<String>,
    pub dns_enhanced_mode: String,
    pub is_saving_dns: bool,
    pub is_saving_fake_ip: bool,
    pub is_saving_tun: bool,
    pub import_url: String,
    pub import_name: String,
    pub import_activate: bool,
    pub is_importing: bool,
    pub local_import_path: String,
    pub local_import_name: String,
    pub local_import_activate: bool,
    pub is_importing_local: bool,
    pub subscription_profile_name: String,
    pub subscription_url: String,
    pub subscription_auto_update_enabled: bool,
    pub subscription_update_interval_hours: String,
    pub is_saving_subscription: bool,
    pub is_updating_subscription_now: bool,
    pub webdav_url: String,
    pub webdav_user: String,
    pub webdav_pass: String,
    pub webdav_enabled: bool,
    pub webdav_sync_interval_mins: String,
    pub webdav_sync_on_startup: bool,
    pub is_syncing: bool,
    pub is_saving_app_settings: bool,
    pub is_admin: bool,
    pub system_proxy_enabled: bool,
    pub autostart_enabled: bool,
    pub installed_kernels: Vec<VersionInfo>,
    pub latest_core_version: Option<String>,
    pub download_progress: f32,
    pub is_checking_update: bool,
    pub last_task_id: usize,
    pub toasts: Vec<(String, ToastStatus)>,
    pub rebuild_flow: RebuildFlowState,
    pub theme: Theme,
    pub fps: u32,
    pub last_frame_time: Instant,
    pub editor_content: text_editor::Content,
    pub editor_path: Option<PathBuf>,
    pub editor_path_setting: String,
}
