use iced::{widget::text_editor, window};
use infiltrator_desktop::MihomoRuntime;
use mihomo_api::{ConnectionSnapshot, Rule, TrafficData};
use mihomo_config::Profile;
use mihomo_version::manager::VersionInfo;
use muda::MenuEvent;
use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Arc;
use tray_icon::TrayIconEvent;

#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub enum Route {
    #[default]
    Overview,
    Profiles,
    Proxies,
    Runtime,
    Rules,
    Dns,
    Sync,
    Editor,
    Settings,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ToastStatus {
    Info,
    Success,
    Warning,
    Error,
}

#[derive(Clone)]
pub enum Message {
    Navigate(Route),
    StartProxy,
    StopProxy,
    ProxyStarted(Result<Arc<MihomoRuntime>, String>),
    ProxyStopped,
    LoadProfiles,
    ProfilesLoaded(Result<Vec<Profile>, String>),
    SetActiveProfile(String),
    UpdateImportUrl(String),
    UpdateImportName(String),
    ImportProfile,
    ProfileImported(Result<(), String>),
    LoadProxies,
    ProxiesLoaded(Result<HashMap<String, mihomo_api::ProxyInfo>, String>),
    SelectProxy(String, String),
    TrafficReceived(TrafficData),
    MemoryReceived(mihomo_api::MemoryData),
    IpInfoReceived(Result<String, String>),
    ConnectionsReceived(ConnectionSnapshot),
    LogReceived(String),
    SetLogLevel(String),
    CloseConnection(String),
    CloseAllConnections,
    FetchRuntimeConfig,
    FetchIpInfo,
    RuntimeConfigFetched(
        Result<
            (
                String,
                bool,
                Vec<String>,
                Vec<String>,
                String,
                String,
                bool,
                bool,
                bool,
            ),
            String,
        >,
    ),
    SetProxyMode(String),
    SetTunEnabled(bool),
    SetTunStack(String),
    SetTunAutoRoute(bool),
    SetTunStrictRoute(bool),
    SetSnifferEnabled(bool),
    ModeSetResult(Result<(), String>),
    OperationResult(Result<(), String>),
    LoadRules,
    RulesLoaded(Result<Vec<Rule>, String>),
    LoadProviders,
    ProvidersLoaded(
        Result<
            (
                Vec<mihomo_api::ProxyProvider>,
                Vec<mihomo_api::RuleProvider>,
            ),
            String,
        >,
    ),
    UpdateProxyProvider(String),
    UpdateRuleProvider(String),
    FilterRules(String),
    TickSubUpdate,
    TickWebDavSync,
    TrayIconEvent(TrayIconEvent),
    MenuEvent(MenuEvent),
    Exit,
    UpdateDnsServer(usize, String),
    UpdateDnsEnhancedMode(String),
    AddDnsServer,
    RemoveDnsServer(usize),
    SaveDns,
    DnsSaved(Result<(), String>),
    SetAutostart(bool),
    AutostartSet(Result<(), String>),
    UpdateWebDavUrl(String),
    UpdateWebDavUser(String),
    UpdateWebDavPass(String),
    SyncUpload,
    SyncDownload,
    SyncFinished(Result<(), String>),
    SetSystemProxy(bool),
    SystemProxySet(Result<(), String>),
    EditProfile(PathBuf),
    ProfileContentLoaded(Result<(PathBuf, String), String>),
    EditorAction(text_editor::Action),
    SaveProfile,
    ProfileSaved(Result<(), String>),
    LoadKernels,
    KernelsLoaded(Result<Vec<VersionInfo>, String>),
    CheckCoreUpdate,
    CoreUpdateInfo(Result<String, String>), // Latest version string
    DownloadCore(String),
    CoreDownloadProgress(f32),
    CoreDownloadFinished(Result<String, String>),
    DeleteKernel(String),
    SetDefaultKernel(String),
    FactoryReset,
    OpenConfigDir,
    FlushFakeIpCache,
    TestProxyDelay(String),
    TestGroupDelay(String),
    WindowClosed(window::Id),
    HideWindow,
    ShowWindow,
    ToggleTheme,
    ShowToast(String, ToastStatus),
    RemoveToast(usize),
}

impl std::fmt::Debug for Message {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Message::Navigate(route) => write!(f, "Navigate({:?})", route),
            Message::StartProxy => write!(f, "StartProxy"),
            Message::StopProxy => write!(f, "StopProxy"),
            Message::ProxyStarted(Ok(_)) => write!(f, "ProxyStarted(Ok)"),
            Message::ProxyStarted(Err(e)) => write!(f, "ProxyStarted(Err({}))", e),
            Message::ProxyStopped => write!(f, "ProxyStopped"),
            Message::LoadProfiles => write!(f, "LoadProfiles"),
            Message::ProfilesLoaded(Ok(p)) => write!(f, "ProfilesLoaded(Ok({} profiles))", p.len()),
            Message::ProfilesLoaded(Err(e)) => write!(f, "ProfilesLoaded(Err({}))", e),
            Message::SetActiveProfile(name) => write!(f, "SetActiveProfile({})", name),
            Message::UpdateImportUrl(url) => write!(f, "UpdateImportUrl({})", url),
            Message::UpdateImportName(name) => write!(f, "UpdateImportName({})", name),
            Message::ImportProfile => write!(f, "ImportProfile"),
            Message::ProfileImported(Ok(_)) => write!(f, "ProfileImported(Ok)"),
            Message::ProfileImported(Err(e)) => write!(f, "ProfileImported(Err({}))", e),
            Message::LoadProxies => write!(f, "LoadProxies"),
            Message::ProxiesLoaded(Ok(p)) => write!(f, "ProxiesLoaded(Ok({} proxies))", p.len()),
            Message::ProxiesLoaded(Err(e)) => write!(f, "ProxiesLoaded(Err({}))", e),
            Message::SelectProxy(g, n) => write!(f, "SelectProxy({}, {})", g, n),
            Message::TrafficReceived(t) => {
                write!(f, "TrafficReceived(up: {}, down: {})", t.up, t.down)
            }
            Message::MemoryReceived(m) => write!(
                f,
                "MemoryReceived(in_use: {}, os_limit: {})",
                m.in_use, m.os_limit
            ),
            Message::IpInfoReceived(Ok(ip)) => write!(f, "IpInfoReceived(Ok({}))", ip),
            Message::IpInfoReceived(Err(e)) => write!(f, "IpInfoReceived(Err({}))", e),
            Message::ConnectionsReceived(c) => write!(
                f,
                "ConnectionsReceived({} connections)",
                c.connections.len()
            ),
            Message::LogReceived(l) => write!(f, "LogReceived({})", l),
            Message::SetLogLevel(l) => write!(f, "SetLogLevel({})", l),
            Message::CloseConnection(id) => write!(f, "CloseConnection({})", id),
            Message::CloseAllConnections => write!(f, "CloseAllConnections"),
            Message::FetchRuntimeConfig => write!(f, "FetchRuntimeConfig"),
            Message::FetchIpInfo => write!(f, "FetchIpInfo"),
            Message::RuntimeConfigFetched(Ok((m, t, d, fb, e, stack, auto, strict, sniff))) => {
                write!(
                    f,
                    "RuntimeConfigFetched({}, {}, {} DNS, {} FB, {}, {}, {}, {}, {})",
                    m,
                    t,
                    d.len(),
                    fb.len(),
                    e,
                    stack,
                    auto,
                    strict,
                    sniff
                )
            }
            Message::RuntimeConfigFetched(Err(e)) => write!(f, "RuntimeConfigFetched(Err({}))", e),
            Message::SetProxyMode(m) => write!(f, "SetProxyMode({})", m),
            Message::SetTunEnabled(t) => write!(f, "SetTunEnabled({})", t),
            Message::SetTunStack(s) => write!(f, "SetTunStack({})", s),
            Message::SetTunAutoRoute(a) => write!(f, "SetTunAutoRoute({})", a),
            Message::SetTunStrictRoute(s) => write!(f, "SetTunStrictRoute({})", s),
            Message::SetSnifferEnabled(s) => write!(f, "SetSnifferEnabled({})", s),
            Message::ModeSetResult(Ok(_)) => write!(f, "ModeSetResult(Ok)"),
            Message::ModeSetResult(Err(e)) => write!(f, "ModeSetResult(Err({}))", e),
            Message::OperationResult(Ok(_)) => write!(f, "OperationResult(Ok)"),
            Message::OperationResult(Err(e)) => write!(f, "OperationResult(Err({}))", e),
            Message::LoadRules => write!(f, "LoadRules"),
            Message::RulesLoaded(Ok(r)) => write!(f, "RulesLoaded(Ok({} rules))", r.len()),
            Message::RulesLoaded(Err(e)) => write!(f, "RulesLoaded(Err({}))", e),
            Message::LoadProviders => write!(f, "LoadProviders"),
            Message::ProvidersLoaded(Ok((p, r))) => write!(
                f,
                "ProvidersLoaded(Ok({} proxies, {} rules))",
                p.len(),
                r.len()
            ),
            Message::ProvidersLoaded(Err(e)) => write!(f, "ProvidersLoaded(Err({}))", e),
            Message::UpdateProxyProvider(name) => write!(f, "UpdateProxyProvider({})", name),
            Message::UpdateRuleProvider(name) => write!(f, "UpdateRuleProvider({})", name),
            Message::FilterRules(s) => write!(f, "FilterRules({})", s),
            Message::TickSubUpdate => write!(f, "TickSubUpdate"),
            Message::TickWebDavSync => write!(f, "TickWebDavSync"),
            Message::TrayIconEvent(_) => write!(f, "TrayIconEvent"),
            Message::MenuEvent(e) => write!(f, "MenuEvent({:?})", e),
            Message::Exit => write!(f, "Exit"),
            Message::UpdateDnsServer(i, s) => write!(f, "UpdateDnsServer({}, {})", i, s),
            Message::UpdateDnsEnhancedMode(m) => write!(f, "UpdateDnsEnhancedMode({})", m),
            Message::AddDnsServer => write!(f, "AddDnsServer"),
            Message::RemoveDnsServer(i) => write!(f, "RemoveDnsServer({})", i),
            Message::SaveDns => write!(f, "SaveDns"),
            Message::DnsSaved(Err(e)) => write!(f, "DnsSaved(Err({}))", e),
            Message::DnsSaved(Ok(_)) => write!(f, "DnsSaved(Ok)"),
            Message::SetAutostart(b) => write!(f, "SetAutostart({})", b),
            Message::AutostartSet(Ok(_)) => write!(f, "AutostartSet(Ok)"),
            Message::AutostartSet(Err(e)) => write!(f, "AutostartSet(Err({}))", e),
            Message::UpdateWebDavUrl(s) => write!(f, "UpdateWebDavUrl({})", s),
            Message::UpdateWebDavUser(s) => write!(f, "UpdateWebDavUser({})", s),
            Message::UpdateWebDavPass(_) => write!(f, "UpdateWebDavPass(***)"),
            Message::SyncUpload => write!(f, "SyncUpload"),
            Message::SyncDownload => write!(f, "SyncDownload"),
            Message::SyncFinished(Ok(_)) => write!(f, "SyncFinished(Ok)"),
            Message::SyncFinished(Err(e)) => write!(f, "SyncFinished(Err({}))", e),
            Message::SetSystemProxy(b) => write!(f, "SetSystemProxy({})", b),
            Message::SystemProxySet(Ok(_)) => write!(f, "SystemProxySet(Ok)"),
            Message::SystemProxySet(Err(e)) => write!(f, "SystemProxySet(Err({}))", e),
            Message::EditProfile(p) => write!(f, "EditProfile({:?})", p),
            Message::ProfileContentLoaded(Ok((p, _))) => {
                write!(f, "ProfileContentLoaded(Ok({:?}))", p)
            }
            Message::ProfileContentLoaded(Err(e)) => write!(f, "ProfileContentLoaded(Err({}))", e),
            Message::EditorAction(_) => write!(f, "EditorAction"),
            Message::SaveProfile => write!(f, "SaveProfile"),
            Message::ProfileSaved(Ok(_)) => write!(f, "ProfileSaved(Ok)"),
            Message::ProfileSaved(Err(e)) => write!(f, "ProfileSaved(Err({}))", e),
            Message::LoadKernels => write!(f, "LoadKernels"),
            Message::KernelsLoaded(Ok(v)) => write!(f, "KernelsLoaded(Ok({} versions))", v.len()),
            Message::KernelsLoaded(Err(e)) => write!(f, "KernelsLoaded(Err({}))", e),
            Message::CheckCoreUpdate => write!(f, "CheckCoreUpdate"),
            Message::CoreUpdateInfo(Ok(v)) => write!(f, "CoreUpdateInfo(Ok({}))", v),
            Message::CoreUpdateInfo(Err(e)) => write!(f, "CoreUpdateInfo(Err({}))", e),
            Message::DownloadCore(v) => write!(f, "DownloadCore({})", v),
            Message::CoreDownloadProgress(p) => write!(f, "CoreDownloadProgress({})", p),
            Message::CoreDownloadFinished(Ok(v)) => write!(f, "CoreDownloadFinished(Ok({}))", v),
            Message::CoreDownloadFinished(Err(e)) => write!(f, "CoreDownloadFinished(Err({}))", e),
            Message::DeleteKernel(v) => write!(f, "DeleteKernel({})", v),
            Message::SetDefaultKernel(v) => write!(f, "SetDefaultKernel({})", v),
            Message::FactoryReset => write!(f, "FactoryReset"),
            Message::OpenConfigDir => write!(f, "OpenConfigDir"),
            Message::FlushFakeIpCache => write!(f, "FlushFakeIpCache"),
            Message::TestProxyDelay(n) => write!(f, "TestProxyDelay({})", n),
            Message::TestGroupDelay(g) => write!(f, "TestGroupDelay({})", g),
            Message::WindowClosed(_) => write!(f, "WindowClosed"),
            Message::HideWindow => write!(f, "HideWindow"),
            Message::ShowWindow => write!(f, "ShowWindow"),
            Message::ToggleTheme => write!(f, "ToggleTheme"),
            Message::ShowToast(s, st) => write!(f, "ShowToast({}, {:?})", s, st),
            Message::RemoveToast(i) => write!(f, "RemoveToast({})", i),
        }
    }
}
